"""Render a draft registry to reviewed-format YAML and validate it.

The emitted text is hand-rendered (PyYAML cannot emit comments, and the
``TODO(review)`` markers ARE the product): a draft must look like a draft.
Everything emitted round-trips through ``yaml.safe_load`` and validates
against ``schema/registry.schema.json`` — ``validate_registry_yaml`` is the
same check the tests and the CLI run.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml
from jsonschema import Draft202012Validator

from stonefold_registry_gen.model import DraftAction, DraftEntity, DraftProperty, DraftRegistry

# Generated text is pure ASCII: drafts get printed to Windows cp1252 consoles
# (same convention as stonefold_demo).
_HEADER = """\
# ---------------------------------------------------------------------------
# DRAFT registry generated by stonefold_registry_gen (source: {source}).
# TODO(review): every kind and attribute below is a machine guess. A human
# MUST review and complete this file before it governs anything:
#   1. fix each action's kind (observe/assess/record/effect/transition);
#   2. assign governance attributes (RFC 01 sec. 5) -- danger is declared,
#      never assumed (docs/06 sec. 4); confirm every suggested reversibility;
#   3. declare from/to states for every transition;
#   4. add connectors/dataSource, scopePredicates, preconditionChecks, hooks,
#      sinks, and namedSets as the policies need them (docs/06 sec. 2, 5);
#   5. validate against schema/registry.schema.json and run the ACP linter.
# ---------------------------------------------------------------------------
"""


def _prop_line(prop: DraftProperty, indent: str) -> str:
    parts = [f"type: {prop.type}"]
    if prop.required:
        parts.append("required: true")
    line = f"{indent}{prop.name}: {{ {', '.join(parts)} }}"
    if prop.hint:
        line += f"   # TODO(review): {prop.hint}"
    return line


def _action_lines(action: DraftAction, indent: str) -> list[str]:
    lines: list[str] = [f"{indent}{action.name}:"]
    kind_comment = ""
    if not action.certain:
        kind_comment = f"   # TODO(review): kind guessed from verb {action.verb!r} -- confirm"
    elif action.kind == "transition":
        kind_comment = "   # TODO(review): declare from/to states (RFC sec. 4.5)"
    lines.append(f"{indent}  kind: {action.kind}{kind_comment}")
    if action.suggested_reversibility:
        lines.append(
            f"{indent}  attributes: {{ reversibility: {action.suggested_reversibility} }}"
            f"   # TODO(review): suggested from verb {action.verb!r} -- confirm"
        )
    if action.data:
        lines.append(f"{indent}  data:")
        for prop in action.data:
            lines.append(_prop_line(prop, indent + "    "))
    if action.hint:
        lines.append(f"{indent}  # TODO(review): {action.hint}")
    return lines


def _entity_lines(entity: DraftEntity) -> list[str]:
    lines: list[str] = [f"  {entity.name}:"]
    if entity.hint:
        lines.append(f"    # {entity.hint}")
    if entity.properties:
        lines.append("    properties:")
        for prop in entity.properties:
            lines.append(_prop_line(prop, "      "))
    else:
        lines.append("    properties: {}   # TODO(review): declare the entity's fields")
    if entity.actions:
        lines.append("    actions:")
        for action in entity.actions:
            lines.extend(_action_lines(action, "      "))
    return lines


def emit_yaml(draft: DraftRegistry) -> str:
    """Render the draft as authoring-format YAML with TODO(review) markers."""
    lines: list[str] = [
        "apiVersion: registry/v1.0",
        f"domain: {draft.domain}",
        _HEADER.format(source=draft.source).rstrip("\n"),
        "",
        "entities:",
        "",
    ]
    for entity in draft.entities:
        lines.extend(_entity_lines(entity))
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def _registry_schema() -> dict[str, Any]:
    # dev/src layout: src/stonefold_registry_gen/emit.py → repo root / schema.
    # Authoring-time tool: run from the repo checkout is the supported mode.
    path = Path(__file__).resolve().parents[2] / "schema" / "registry.schema.json"
    return dict(json.loads(path.read_text(encoding="utf-8")))


def validate_registry_yaml(text: str) -> list[str]:
    """Return schema-validation problems for an emitted draft (empty = valid)."""
    try:
        doc = yaml.safe_load(text)
    except yaml.YAMLError as exc:  # a generator bug, not a user error
        return [f"emitted text is not valid YAML: {exc}"]
    validator = Draft202012Validator(_registry_schema())
    return [
        f"{'/'.join(str(p) for p in err.absolute_path) or '<root>'}: {err.message}"
        for err in validator.iter_errors(doc)
    ]
